name: Docker Build

on:
  pull_request:
  push:
    branches:
      - master
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        if: ${{ github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/stable' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/stable' }}
          platforms: linux/amd64,linux/arm64
          target: web
          tags: ghcr.io/datenknoten/phorge
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/stable' }}
          platforms: linux/amd64,linux/arm64
          target: daemon
          tags: ghcr.io/datenknoten/phorge-daemon
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/stable' }}
          platforms: linux/amd64,linux/arm64
          target: aphlict
          tags: ghcr.io/datenknoten/phorge-aphlict
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/stable' }}
          platforms: linux/amd64,linux/arm64
          target: sshd
          tags: ghcr.io/datenknoten/phorge-sshd
