name: Docker Build

on:
  pull_request:
  push:
    branches:
      - master
      - stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: ${{ github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/stable' }}
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: docker/build-push-action@v5
        name: Build web image
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/stable' }}
          platforms: linux/amd64,linux/arm64
          target: web
          tags: ghcr.io/datenknoten/phorge
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/build-push-action@v5
        name: Build daemon image
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/stable' }}
          platforms: linux/amd64,linux/arm64
          target: daemon
          tags: ghcr.io/datenknoten/phorge-daemon
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/build-push-action@v5
        name: Build aphlict image
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/stable' }}
          platforms: linux/amd64,linux/arm64
          target: aphlict
          tags: ghcr.io/datenknoten/phorge-aphlict
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - uses: docker/build-push-action@v5
        name: Build sshd image
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/stable' }}
          platforms: linux/amd64,linux/arm64
          target: sshd
          tags: ghcr.io/datenknoten/phorge-sshd
          cache-from: type=gha
          cache-to: type=gha,mode=max
