name: Update

on:
  schedule:
    - cron: '22 * * * *'

jobs:
  update:

    runs-on: ubuntu-latest
    
    strategy:
      matrix: 
        branch: ['master']

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ matrix.branch }}
          fetch-depth: 0
          submodules: 'recursive'
      - name: 'Pull Submodules & Commit Changes'
        run: |
          git submodule --quiet foreach git checkout --quiet origin/${{ matrix.branch }}
          if ! (git diff --quiet) then
            git checkout -B ${{ matrix.branch }}
            git config --global user.name "Phorge Docker"
            git config --global user.email "phorge-docker@users.noreply.github.com"
            git commit --all -m "Update Phorge"
            git push origin ${{ matrix.branch }}
          fi
